SPK_NAME = par2cmdline
SPK_VERS = 0.8.0
SPK_REV = 3
SPK_ICON = src/par2cmdline.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER  = Johan Vromans
DESCRIPTION = Par2Cmdline is a PAR 2.0 compatible file verification and repair tool. It provides command line tools par2, par2create, par2verify and par2repair.
RELOAD_UI   = no
DISPLAY_NAME = Par2Cmdline
WHEELS      =
STARTABLE   = no
CHANGELOG   = "Upgrade to 0.8.0"

HOMEPAGE    = https://github.com/parchive/par2cmdline
LICENSE     = GPLv2

INSTALLER_SCRIPT = src/install.sh

include ../../mk/spksrc.spk.mk
