SPK_NAME = atop
SPK_VERS = 2.5.0
SPK_REV = 1
SPK_ICON = src/atop.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = Johan Vromans
DESCRIPTION = ASCII full-screen performance monitor 
RELOAD_UI = no
DISPLAY_NAME = atop
STARTABLE = no
CHANGELOG = "initial version"

HOMEPAGE   = https://github.com/Atoptool/atop
LICENSE    = GPLv2

INSTALLER_SCRIPT = src/installer.sh
INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
